{capture name="mainbox"}

    {if $filter_data.combination_id}
        {assign var="id" value=$filter_data.combination_id}
    {else}
        {assign var="id" value=0}
    {/if}
    
    <form id="form" action="{""|fn_url}" method="post" name="filter_combination_update_form" class="form-horizontal form-edit cm-disable-empty-files">
        <input type="hidden" name="fake" value="1" />
        <input type="hidden" name="combination_id" value="{$id}" />
        
        <div class="control-group">
            <a href="{"seo_filters.manage"|fn_url}">{__("all_combinations")}</a>
        </div>
        
        {include file="common/subheader.tpl" title=__("information") target="#acc_information"}
        
        <div id="acc_information" class="collapse in">
            
            <div class="control-group {$no_hide_input_if_shared_product}" id="combination_categories">
                {math equation="rand()" assign="rnd"}
                {if $smarty.request.category_id}
                    {assign var="request_category_id" value=","|explode:$smarty.request.category_id}
                {else}
                    {assign var="request_category_id" value=""}
                {/if}
                <label for="ccategories_{$rnd}_ids" class="control-label{if $filter_data.autogenerated != "Y"} cm-required{/if}">{__("category")}</label>
                <div class="controls">
                    {include file="pickers/categories/picker.tpl" rnd=$rnd data_id="categories" hide_input="Y" input_name="filter_data[category_ids]" item_ids=$filter_data.category_ids|default:$request_category_id hide_link=true hide_delete_button=true display_input_id="category_ids" multiple=false disable_no_item_text=true view_mode="mixed" but_meta="btn"}
                </div>
            <!--combination_categories--></div>
        
            <div class="control-group">
                <label for="filter_combination_name" class="control-label cm-required">{__("name")}</label>
                <div class="controls">
                    <input class="input-large" form="form" type="text" name="filter_data[combination_name]" id="filter_combination_name" value="{$filter_data.combination_name}" />
                </div>
            </div>
            <div class="control-group">
                <label for="filter_combination_name_seo" class="control-label">{__("combination_seo_name")}</label>
                <div class="controls">
                    <input class="input-large" form="form" type="text" name="filter_data[combination_seo_name]" id="filter_combination_name_seo" value="{$filter_data.combination_seo_name}" />
                </div>
            </div>
            
            <div class="control-group">
                <label for="filter_category_display_name" class="control-label cm-required">{__("category_name")}</label>
                <div class="controls">
                    <input class="input-large" form="form" type="text" name="filter_data[category_display_name]" id="filter_category_display_name" value="{$filter_data.category_display_name}" />
                </div>
            </div>
            
            <div class="control-group {if $share_dont_hide}cm-no-hide-input{/if}">
                <label class="control-label" for="elm_seo_name">{__("seo_name")}:</label>
                <div class="controls">
            
                    {assign var="parent_uri" value=$filter_data.category_ids|fn_seo_filters_get_seo_parent_uri:$smarty.const.DESCR_SL}
                    <span class="cm-field-prefix">{$parent_uri.prefix}</span>
                    <input type="text" name="filter_data[seo_name]" id="filter_combination_name_seo" size="10" value="{$filter_data.seo_name}" class="input-long{if $filter_data.autogenerated != "Y"} cm-seo-check-changed{/if}" />
                    <span class="cm-field-suffix">{$parent_uri.suffix}</span>
                    {if $filter_data.autogenerated != "Y"}
                    <div class="hidden cm-seo-check-changed-block">
                        <input type="hidden" name="filter_data[seo_create_redirect]" disabled="disabled" value="0" />
                        <label class="checkbox inline"><input type="checkbox" name="filter_data[seo_create_redirect]" value="1" checked="checked" disabled="disabled" />{__("seo.create_redirect")}</label>
                    </div>
                    {/if}
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label" for="elm_category_descr">{__("description")}:</label>
                <div class="controls">
                    <textarea id="elm_category_descr" name="filter_data[description]" cols="55" rows="8" class="input-large cm-wysiwyg input-textarea-long">{$filter_data.description}</textarea>
                </div>
            </div>
        
        </div>
        {if $id}
        {include file="common/subheader.tpl" title=__("filter_combinations") target="#acc_filter_combinations"}
        
        <div id="acc_filter_combinations" class="collapse in">
            {if $filter_data.combination_description}
            <div class="control-group">
                <label class="control-label">{__("current_combination")}:</label>
                <div class="controls">
                    {foreach from=$filter_data.combination_description item="filter"}
                        {if $filter.type == "price"}
                            <p><strong>{$filter.name}</strong>:&nbsp;{$filter.value}&nbsp;({$currencies.$primary_currency.symbol nofilter})</p>
                        {elseif $filter.type == "number"}
                            <p><strong>{$filter.name}</strong>:&nbsp;{$filter.value}</p>
                        {else}
                            {if $filter.variants}
                                <p><strong>{$filter.name}</strong>:&nbsp;{implode(", ", $filter.variants)}</p>
                            {/if}                        
                        {/if}
                    {/foreach}
                </div>
            </div>
            {/if}
            {if !$filter_data.category_ids}<div class="hidden">{/if}
            <div class="control-group">
                <label class="control-label">{__("filter_combinations")}</label>
                <div class="controls">
                    {include file="addons/seo_filters/views/seo_filters/components/filters_grid.tpl" data_name="filter_data[combinations]" filter_features=$filter_items}
                </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{__("price")}&nbsp;({$currencies.$primary_currency.symbol nofilter})</label>
                <div class="controls">
                    <input type="text" name="filter_data[price_from]" size="1" value="{$filter_data.price_from}" onfocus="this.select();" class="input-small" /> - <input type="text" size="1" name="filter_data[price_to]" value="{$filter_data.price_to}" onfocus="this.select();" class="input-small" />
                </div>
            </div>
            {if !$filter_data.category_ids}</div>{/if}
        </div>
        {/if}
        {include file="common/subheader.tpl" title=__("seo_meta_data") target="#acc_seo_meta"}
        
            <div id="acc_seo_meta" class="collapse in">
                <div class="control-group">
                    <label class="control-label" for="elm_product_page_title">{__("page_title")}:</label>
                    <div class="controls">
                        <input type="text" name="filter_data[page_title]" id="elm_product_page_title" size="55" value="{$filter_data.page_title}" class="input-large" />
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="elm_product_meta_descr">{__("meta_description")}:</label>
                    <div class="controls">
                        <textarea name="filter_data[meta_description]" id="elm_product_meta_descr" cols="55" rows="2" class="input-large">{$filter_data.meta_description}</textarea>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="elm_product_meta_keywords">{__("meta_keywords")}:</label>
                    <div class="controls">
                        <textarea name="filter_data[meta_keywords]" id="elm_product_meta_keywords" cols="55" rows="2" class="input-large">{$filter_data.meta_keywords}</textarea>
                    </div>
                </div>
            </div>
        
    </form>
    
{/capture}

{capture name="buttons"}
    {if $id}
        {capture name="tools_list"}
            <li>{btn type="list" text=__("delete") class="cm-confirm cm-post" href="seo_filters.delete?combination_id=`$id`"}</li>
            {if $view_uri}
                <li>{btn type="list" target="_blank" text=__("preview") href=$view_uri}</li>
            {/if}
        {/capture}
        {dropdown content=$smarty.capture.tools_list}
    {/if}
    {include file="buttons/save_cancel.tpl" but_role="submit-link" but_name="dispatch[seo_filters.update]" but_target_form="filter_combination_update_form" save=$id}
{/capture}

{if $id}
    {capture name="mainbox_title"}
        {"{__("editing_seo_filter")}: `$filter_data.combination_name`"|strip_tags}
    {/capture}
{else}
    {capture name="mainbox_title"}
        {__("new_seo_filter")|strip_tags}
    {/capture}
{/if}

{include file="common/mainbox.tpl" title=$smarty.capture.mainbox_title content=$smarty.capture.mainbox select_languages=$id buttons=$smarty.capture.buttons}